"""
Module: FermionicLatticeSurgery
"""
import copy
import networkx as nx
import numpy as np
from extendedstim.Code.BeyondCode.SubsystemCode import SubsystemCode
from extendedstim.Code.PrimitiveCode.MajoranaCSSCode import MajoranaCSSCode
from extendedstim.Code.PrimitiveCode.MajoranaCode import MajoranaCode
from extendedstim.Code.CodeFactory.ColorCode import MajoranaColorCode
from extendedstim.Physics.MajoranaOperator import MajoranaOperator


class FermionicLatticeSurgery:

    ##  CHAPTER: ====Details====


    def __init__(self, code_A: MajoranaCSSCode, index_A: int, code_B: MajoranaCSSCode | None = None, index_B: int | None = None) -> None:
        """
        Construct lattice surgery code for measuring joint logical observable.
        input.code_A: Majorana CSS Code.
        input.index_A: Index of logical observable in code_A.
        input.code_B: Majorana CSS Code.
        input.index_B: Index of logical observable in code_B.
        output: None.
        influence: None
        """

        ##  SECTION: ----Details----
        ##  stabilizers
        self.observable: None | MajoranaOperator = None  # Joint logical observable to be measured
        self.related_stabilizers_A_x = []
        self.related_stabilizers_B_x = []
        self.related_stabilizers_A_z = []
        self.related_stabilizers_B_z = []
        self.irrelated_stabilizers_A_z = []
        self.irrelated_stabilizers_B_z = []
        self.irrelated_stabilizers_A_x = []
        self.irrelated_stabilizers_B_x = []

        ##  ancilla
        self.ancilla_number = 0  # Number of ancilla sites generated during lattice surgery
        self.ancilla_stabilizers = []  # Initial ancilla stabilizers

        ##  stabilizers
        self.modify_stabilizers_A = []  # Modified stabilizers in code_A
        self.modify_stabilizers_B = []  # Modified stabilizers in code_B
        self.gauge_stabilizers = []  # Gauge stabilizers generated by lattice surgery
        self.measurement_stabilizers = []  # Measurement stabilizers generated by lattice surgery

        ##  SECTION: ----Details----
        if index_B is None or code_B is None:
            self.code_A: MajoranaCSSCode = code_A
            self.index_A: int = index_A
            self.code_B: MajoranaColorCode = MajoranaColorCode(code_A.logical_operators_x[self.index_A].weight)
            self.index_B: int = 0
            self._ZechuanLatticeSurgery()
        else:
            if code_A.logical_operators_x[index_A].weight > code_B.logical_operators_x[index_B].weight:
                self.code_A: MajoranaCSSCode = code_A.copy()
                self.code_B: MajoranaCSSCode = code_B.copy()
                self.index_A: int = index_A
                self.index_B: int = index_B
            else:
                self.code_A: MajoranaCSSCode = code_B.copy()
                self.code_B: MajoranaCSSCode = code_A.copy()
                self.index_A: int = index_B
                self.index_B: int = index_A
            self._MajoranaLatticeSurgery()
        self.physical_number = code_A.physical_number + self.code_B.physical_number + self.ancilla_number

        ##  SECTION: ----Details----
        self.code = MajoranaCode(self.irrelated_stabilizers_A_z + self.irrelated_stabilizers_B_z + self.irrelated_stabilizers_A_x + self.irrelated_stabilizers_B_x +
                                 self.related_stabilizers_A_z + self.related_stabilizers_B_z +
                                 self.modify_stabilizers_A + self.modify_stabilizers_B + self.gauge_stabilizers, self.physical_number)
        self.code_before_surgery = MajoranaCSSCode([MajoranaOperator.HermitianOperatorFromOccupy(temp.occupy_x, []) for temp in self.code_A.generators_x] + [MajoranaOperator.HermitianOperatorFromOccupy(temp.occupy_x + code_A.physical_number, []) for temp in self.code_B.generators_x],
                                                   [MajoranaOperator.HermitianOperatorFromOccupy([], temp.occupy_z) for temp in self.code_A.generators_z] + [MajoranaOperator.HermitianOperatorFromOccupy([], temp.occupy_z + code_A.physical_number) for temp in self.code_B.generators_z],
                                                   self.code_A.physical_number + self.code_B.physical_number)
        self.code_after_surgery = MajoranaCode(self.irrelated_stabilizers_A_x + self.irrelated_stabilizers_B_x +
                                               self.irrelated_stabilizers_A_z + self.irrelated_stabilizers_B_x +
                                               self.related_stabilizers_A_z + self.related_stabilizers_B_z +
                                               self.modify_stabilizers_A + self.modify_stabilizers_B + self.measurement_stabilizers + self.gauge_stabilizers, self.physical_number)

        ##  bare logical operators
        self.bare_logical_operators_x = []
        self.bare_logical_operators_z = []
        for i in range(len(self.code_A.logical_operators_x)):
            if i != self.index_A:
                self.bare_logical_operators_z.append(self.code_A.logical_operators_z[i])
                self.bare_logical_operators_x.append(self.code_A.logical_operators_x[i])
        for i in range(len(self.code_B.logical_operators_x)):
            if i != self.index_B:
                self.bare_logical_operators_z.append(MajoranaOperator.HermitianOperatorFromOccupy([], self.code_B.logical_operators_z[i].occupy_z + self.code_A.physical_number))
                self.bare_logical_operators_x.append(MajoranaOperator.HermitianOperatorFromOccupy(self.code_B.logical_operators_x[i].occupy_x + self.code_A.physical_number, []))
        self.remain_bare_logical_operator = MajoranaOperator.HermitianOperatorFromOccupy([], np.hstack([self.code_A.logical_operators_z[self.index_A].occupy_z, self.code_B.logical_operators_z[self.index_B].occupy_z + self.code_A.physical_number]))

        self.subsystem_code = SubsystemCode(self.code, self.bare_logical_operators_x + self.bare_logical_operators_z)

    ##  CHAPTER: ====Details====


    def _MajoranaLatticeSurgery(self):
        code_A: MajoranaCSSCode = self.code_A.copy()
        code_B: MajoranaCSSCode = self.code_B.copy()
        assert isinstance(code_A, MajoranaCSSCode)
        assert isinstance(code_B, MajoranaCSSCode)
        assert isinstance(self.index_A, int)
        assert isinstance(self.index_B, int)

        ##  SECTION: ----Details----
        ##  joint code block
        majorana_number_A = code_A.physical_number
        majorana_number_B = code_B.physical_number
        logical_operator_A = code_A.logical_operators_x[self.index_A]
        logical_operator_B = code_B.logical_operators_x[self.index_B]
        logical_operator_B.occupy_x = logical_operator_B.occupy_x + majorana_number_A
        self.observable = 1j * logical_operator_A @ logical_operator_B
        code_A.index_map(np.arange(majorana_number_A), majorana_number_A + majorana_number_B)
        code_B.index_map(np.arange(majorana_number_A, majorana_number_A + majorana_number_B), majorana_number_A + majorana_number_B)

        ##  generators
        self.related_stabilizers_A_x = copy.deepcopy([temp for temp in code_A.generators if len(set(temp.occupy_x) & set(logical_operator_A.occupy_x)) > 0])
        self.related_stabilizers_B_x = copy.deepcopy([temp for temp in code_B.generators if len(set(temp.occupy_x) & set(logical_operator_B.occupy_x)) > 0])
        self.related_stabilizers_A_z = copy.deepcopy([temp for temp in code_A.generators_z if len(set(temp.occupy_z) & set(logical_operator_A.occupy_x)) > 0])
        self.related_stabilizers_B_z = copy.deepcopy([temp for temp in code_B.generators_z if len(set(temp.occupy_z) & set(logical_operator_B.occupy_x)) > 0])
        self.irrelated_stabilizers_A_z = copy.deepcopy([temp for temp in code_A.generators_z if len(set(temp.occupy_z) & set(logical_operator_A.occupy_x)) == 0])
        self.irrelated_stabilizers_B_z = copy.deepcopy([temp for temp in code_B.generators_z if len(set(temp.occupy_z) & set(logical_operator_B.occupy_x)) == 0])
        self.irrelated_stabilizers_A_x = copy.deepcopy([temp for temp in code_A.generators_x if len(set(temp.occupy_x) & set(logical_operator_A.occupy_x)) == 0])
        self.irrelated_stabilizers_B_x = copy.deepcopy([temp for temp in code_B.generators_x if len(set(temp.occupy_x) & set(logical_operator_B.occupy_x)) == 0])

        ##  SECTION: ----Details----
        ancilla_mode_number = 0

        ##  A stabilizers ancilla
        for i in range(len(self.related_stabilizers_A_x)):
            result_temp = [ancilla_mode_number + temp for temp in range(len(set(self.related_stabilizers_A_x[i].occupy_x) & set(logical_operator_A.occupy_x)))]  # Give new ancilla modes indices
            self.modify_stabilizers_A.append([self.related_stabilizers_A_x[i].occupy_x.tolist(), result_temp])
            ancilla_mode_number += len(result_temp)

        ##  B stabilizers ancilla
        for i in range(len(self.related_stabilizers_B_x)):
            result_temp = [ancilla_mode_number + temp for temp in range(len(set(self.related_stabilizers_B_x[i].occupy_x) & set(logical_operator_B.occupy_x)))]  # Give new ancilla modes indices
            self.modify_stabilizers_B.append([self.related_stabilizers_B_x[i].occupy_x.tolist(), result_temp])
            ancilla_mode_number += len(result_temp)

        ##  SECTION: ----Details----
        for i in range(len(logical_operator_B.occupy_x)):
            self.measurement_stabilizers.append([[logical_operator_A.occupy_x[i], logical_operator_B.occupy_x[i]], []])
        for i in range((len(logical_operator_A.occupy_x) - len(logical_operator_B.occupy_x)) // 2):
            self.measurement_stabilizers.append([[logical_operator_A.occupy_x[2 * i + len(logical_operator_B.occupy_x)], logical_operator_A.occupy_x[2 * i + len(logical_operator_B.occupy_x) + 1]], []])

        ##  A modified stabilizers measurement stabilizer measurement stabilizer ancilla modes
        for i in range(len(self.modify_stabilizers_A)):
            flag_temp = 0  # Record which ancilla mode is currently used
            for j in range(len(self.measurement_stabilizers)):
                number = len(set(self.modify_stabilizers_A[i][0]) & set(self.measurement_stabilizers[j][0]))
                self.measurement_stabilizers[j][1] = self.measurement_stabilizers[j][1] + [self.modify_stabilizers_A[i][1][flag_temp + k] for k in range(number)]
                flag_temp += number

        ##  B modified stabilizers measurement stabilizer measurement stabilizer ancilla modes
        for i in range(len(self.modify_stabilizers_B)):
            flag_temp = 0  # Record which ancilla mode is currently used
            for j in range(len(self.measurement_stabilizers)):
                number = len(set(self.modify_stabilizers_B[i][0]) & set(self.measurement_stabilizers[j][0]))
                self.measurement_stabilizers[j][1] = self.measurement_stabilizers[j][1] + [self.modify_stabilizers_B[i][1][flag_temp + k] for k in range(number)]
                flag_temp += number

        ##  odd-weight measurement stabilizers
        single_mode_list = []
        for i in range(len(self.measurement_stabilizers)):
            if len(self.measurement_stabilizers[i][1]) % 2 != 0:
                self.measurement_stabilizers[i][1].append(ancilla_mode_number)
                single_mode_list.append(ancilla_mode_number)
                ancilla_mode_number += 1

        ##  SECTION: ----Details----
        mode_vertices = ['Mode' + str(temp) for temp in range(ancilla_mode_number)]
        A_vertices = []
        B_vertices = []
        measurement_vertices = []
        edges = []

        ##  A modified stabilizer nodes edges
        for i in range(len(self.modify_stabilizers_A)):
            if len(self.modify_stabilizers_A[i][1]) // 2 == 1:
                A_vertices.append('A' + str(i))
                edges.append(('A' + str(i), 'Mode' + str(self.modify_stabilizers_A[i][1][0])))
                edges.append(('A' + str(i), 'Mode' + str(self.modify_stabilizers_A[i][1][1])))
            else:
                for j in range(len(self.modify_stabilizers_A[i][1]) // 2):
                    A_vertices.append('A' + str(i) + '_' + str(j))
                    edges.append(('A' + str(i), 'Mode' + str(self.modify_stabilizers_A[i][1][j * 2])))
                    edges.append(('A' + str(i), 'Mode' + str(self.modify_stabilizers_A[i][1][j * 2 + 1])))

        ##  B modified stabilizer nodes edges
        for i in range(len(self.modify_stabilizers_B)):
            if len(self.modify_stabilizers_B[i][1]) // 2 == 1:
                B_vertices.append('B' + str(i))
                edges.append(('B' + str(i), 'Mode' + str(self.modify_stabilizers_B[i][1][0])))
                edges.append(('B' + str(i), 'Mode' + str(self.modify_stabilizers_B[i][1][1])))
            else:
                for j in range(len(self.modify_stabilizers_B[i][1]) // 2):
                    B_vertices.append('B' + str(i) + '_' + str(j))
                    edges.append(('B' + str(i), 'Mode' + str(self.modify_stabilizers_B[i][1][j * 2])))
                    edges.append(('B' + str(i), 'Mode' + str(self.modify_stabilizers_B[i][1][j * 2 + 1])))

        ##  measurement stabilizer nodes edges
        for i in range(len(self.measurement_stabilizers)):
            measurement_vertices.append('Measure' + str(i))
            for j in range(len(self.measurement_stabilizers[i][1])):
                edges.append(('Measure' + str(i), 'Mode' + str(self.measurement_stabilizers[i][1][j])))

        ##  single ancilla mode virtual edges
        virtual_vertices = []
        for i in range(len(single_mode_list) // 2):
            virtual_vertices.append('Virtual' + str(i))
            edges.append(('Virtual' + str(i), 'Mode' + str(single_mode_list[i])))
            edges.append(('Virtual' + str(i), 'Mode' + str(single_mode_list[i])))

        graph = nx.Graph()
        graph.add_nodes_from(mode_vertices)
        graph.add_nodes_from(A_vertices)
        graph.add_nodes_from(B_vertices)
        graph.add_nodes_from(measurement_vertices)
        graph.add_nodes_from(virtual_vertices)
        graph.add_edges_from(edges)
        cyclic_basis = nx.minimum_cycle_basis(graph)
        for i in range(len(cyclic_basis)):
            modes_temp = []
            for j in range(len(cyclic_basis[i])):
                if 'Mode' in cyclic_basis[i][j]:
                    modes_temp.append(int(cyclic_basis[i][j][4:]))
            self.gauge_stabilizers.append([[], modes_temp])

        ##  SECTION: ----Details----
        alls = [self.modify_stabilizers_A, self.modify_stabilizers_B, self.measurement_stabilizers, self.gauge_stabilizers]
        for i in range(len(alls)):
            for j in range(len(alls[i])):
                occupy_x_temp = alls[i][j][0] + [temp // 2 + majorana_number_A + majorana_number_B for temp in alls[i][j][1] if temp % 2 == 0]
                occupy_z_temp = [temp // 2 + majorana_number_A + majorana_number_B for temp in alls[i][j][1] if temp % 2 == 1]
                alls[i][j] = MajoranaOperator.HermitianOperatorFromOccupy(occupy_x_temp, occupy_z_temp)
        self.ancilla_number = ancilla_mode_number // 2

    ##  CHAPTER: ====Details====


    def _ZechuanLatticeSurgery(self):

        ##  SECTION: ----Details----
        code_A: MajoranaCSSCode = self.code_A.copy()
        code_B: MajoranaColorCode = self.code_B.copy()
        majorana_number_A = code_A.physical_number
        majorana_number_B = code_B.physical_number
        logical_operator_A = code_A.logical_operators_x[self.index_A]
        logical_operator_B = code_B.logical_operators_x[0]
        logical_operator_B.occupy_x = logical_operator_B.occupy_x + majorana_number_A
        self.observable = 1j * logical_operator_A @ logical_operator_B
        code_A.index_map(np.arange(majorana_number_A), majorana_number_A + majorana_number_B)
        code_B.index_map(np.arange(majorana_number_A, majorana_number_A + majorana_number_B), majorana_number_A + majorana_number_B)

        self.related_stabilizers_A_x = copy.deepcopy([temp for temp in code_A.generators if len(set(temp.occupy_x) & set(logical_operator_A.occupy_x)) > 0])
        self.related_stabilizers_B_x = copy.deepcopy([temp for temp in code_B.generators if len(set(temp.occupy_x) & set(logical_operator_B.occupy_x)) > 0])
        self.irrelated_stabilizers_A_z = copy.deepcopy([temp for temp in code_A.generators_z if len(set(temp.occupy_z) & set(logical_operator_A.occupy_x)) == 0])
        self.irrelated_stabilizers_B_z = copy.deepcopy([temp for temp in code_B.generators_z if len(set(temp.occupy_z) & set(logical_operator_B.occupy_x)) == 0])
        self.irrelated_stabilizers_A_x = copy.deepcopy([temp for temp in code_A.generators_x if len(set(temp.occupy_x) & set(logical_operator_A.occupy_x)) == 0])
        self.irrelated_stabilizers_B_x = copy.deepcopy([temp for temp in code_B.generators_x if len(set(temp.occupy_x) & set(logical_operator_B.occupy_x)) == 0])

        ancilla_mode_number = 0
        edge_site_bin_A: list[list[int]] = [[] for _ in range(code_B.d)]
        edge_site_bin_B: list[list[int]] = [[] for _ in range(code_B.d)]
        used_flags = [False for _ in range(code_B.d - 1)]

        ##  stabilizers ancilla
        for i in range(len(self.related_stabilizers_A_x)):
            overlaps = list(set(self.related_stabilizers_A_x[i].occupy_x) & set(logical_operator_A.occupy_x))
            for j in range(len(overlaps) // 2):
                index_0 = int(np.where(logical_operator_A.occupy_x == overlaps[2 * j])[0][0])
                index_1 = int(np.where(logical_operator_A.occupy_x == overlaps[2 * j + 1])[0][0])
                edge_site_bin_A[index_0].append(ancilla_mode_number)
                edge_site_bin_A[index_1].append(ancilla_mode_number + 1)
                self.modify_stabilizers_A.append([self.related_stabilizers_A_x[i].occupy_x.tolist(), [ancilla_mode_number, ancilla_mode_number + 1]])
                self.related_stabilizers_A_z.append(MajoranaOperator.HermitianOperatorFromOccupy([], self.related_stabilizers_A_x[i].occupy_x.tolist()))
                edge_site_bin_B[index_0].append(ancilla_mode_number + 2)
                edge_site_bin_B[index_1].append(ancilla_mode_number + 3)
                B_temp = get_between(code_B, index_0, index_1)
                self.related_stabilizers_B_z.append(MajoranaOperator.HermitianOperatorFromOccupy([], [temp for temp in B_temp.occupy_x]))
                self.modify_stabilizers_B.append([[temp for temp in B_temp.occupy_x], [ancilla_mode_number + 2, ancilla_mode_number + 3]])
                small = min(index_0, index_1)
                big = max(index_0, index_1)
                used_flags[small] = True
                used_flags[big - 1] = True
                self.gauge_stabilizers.append([[], [ancilla_mode_number + temp for temp in range(4)]])
                ancilla_mode_number += 4

        ##  edge stabilizers
        for i in range(len(used_flags)):
            if not used_flags[i]:
                edge_site_bin_B[i].append(ancilla_mode_number)
                edge_site_bin_B[i].append(ancilla_mode_number + 1)
                edge_site_bin_B[i + 1].append(ancilla_mode_number + 2)
                edge_site_bin_B[i + 1].append(ancilla_mode_number + 3)
                self.modify_stabilizers_B.append([get_between(code_B, i, i + 1).occupy_x.tolist(), [ancilla_mode_number, ancilla_mode_number + 2]])
                self.gauge_stabilizers.append([[], [ancilla_mode_number + temp for temp in range(4)]])
                ancilla_mode_number += 4

        ##  measurement stabilizers
        for i in range(len(edge_site_bin_A)):
            self.measurement_stabilizers.append(([logical_operator_A.occupy_x[i], logical_operator_B.occupy_x[i]], edge_site_bin_A[i] + edge_site_bin_B[i]))

        ##  SECTION: ----Details----
        alls = [self.modify_stabilizers_A, self.modify_stabilizers_B, self.measurement_stabilizers, self.gauge_stabilizers]
        for i in range(len(alls)):
            for j in range(len(alls[i])):
                occupy_x_temp = alls[i][j][0] + [temp // 2 + majorana_number_A + majorana_number_B for temp in alls[i][j][1] if temp % 2 == 0]
                occupy_z_temp = [temp // 2 + majorana_number_A + majorana_number_B for temp in alls[i][j][1] if temp % 2 == 1]
                alls[i][j] = MajoranaOperator.HermitianOperatorFromOccupy(occupy_x_temp, occupy_z_temp)
        self.ancilla_number = ancilla_mode_number // 2


def get_between(color_code: MajoranaColorCode, index_0: int, index_1: int):
    """
    input.index_0: int, index of the site.
    input.index_1: int, index of the site.
    output: MajoranaOperator, stabilizer between index_0 and index_1.
    influence: None
    """
    edge_stabilizers = []
    for i in range(color_code.d // 2):
        edge_stabilizers.append(color_code.generators_x[0:color_code.d][i])
        edge_stabilizers.append(color_code.generators_x[0:color_code.d][i + color_code.d // 2])
    if index_0 > index_1:
        aa = index_1
        bb = index_0
    else:
        aa = index_0
        bb = index_1
    assert 0 <= index_0 < color_code.d
    assert 0 <= index_1 < color_code.d
    if aa == bb - 1:
        return edge_stabilizers[aa].copy()
    else:
        return edge_stabilizers[aa] @ edge_stabilizers[bb - 1]
